use std::io::Write;
use std::path::PathBuf;
use std::process::Command as ProcessCommand;

use directories::BaseDirs;

use crate::db::connection::Database;
use crate::db::tracker_repo::TrackerRepo;
use crate::error::{AppError, Result};

pub fn sync(db: &Database) -> Result<()> {
    let repo = TrackerRepo::new(db);
    let trackers = repo.get_all()?;

    let content = generate_bindings_content(&trackers);
    let bindings_path = get_bindings_path()?;

    std::fs::write(&bindings_path, &content)?;
    ensure_hyprland_source(&bindings_path)?;
    reload_hyprland();

    Ok(())
}

fn generate_bindings_content(trackers: &[crate::domain::tracker::Tracker]) -> String {
    let mut lines = vec![
        "# Auto-generated by tag-tracker. Do not edit manually.".to_string(),
        "bindd = SUPER ALT CTRL, 0, Pause tracker, exec, tag-tracker pause".to_string(),
    ];

    for tracker in trackers {
        if let Some(shortcut) = tracker.shortcut {
            lines.push(format!(
                "bindd = SUPER ALT CTRL, {}, Tracker: {}, exec, tag-tracker activate \"{}\"",
                shortcut, tracker.name, tracker.name
            ));
        }
    }

    lines.join("\n") + "\n"
}

fn get_bindings_path() -> Result<PathBuf> {
    let base = BaseDirs::new()
        .ok_or_else(|| AppError::Validation("Could not determine config directory.".into()))?;
    Ok(base.config_dir().join("hypr/tag-tracker-bindings.conf"))
}

fn ensure_hyprland_source(bindings_path: &PathBuf) -> Result<()> {
    let base = BaseDirs::new()
        .ok_or_else(|| AppError::Validation("Could not determine config directory.".into()))?;
    let hyprland_conf = base.config_dir().join("hypr/hyprland.conf");

    if !hyprland_conf.exists() {
        return Ok(());
    }

    let content = std::fs::read_to_string(&hyprland_conf)?;
    let source_line = format!("source = {}", bindings_path.display());

    if !content.contains(&source_line) {
        let mut file = std::fs::OpenOptions::new()
            .append(true)
            .open(&hyprland_conf)?;
        writeln!(file, "\n# Tag-tracker keyboard shortcuts")?;
        writeln!(file, "{source_line}")?;
    }
    Ok(())
}

fn reload_hyprland() {
    let _ = ProcessCommand::new("hyprctl").arg("reload").status();
}

pub fn bindings_file_exists() -> bool {
    get_bindings_path().map(|p| p.exists()).unwrap_or(false)
}
